##
# NOTE: any changes to the event triggers or the paths here should be reflected in:
#       golangci-lint-paths-ignore.yml
##

name: golangci-lint

on:
  push:
    branches:
      - staging
      - trying
      - rollup
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - '.golangci.yml'
  pull_request:
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - '.golangci.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: lint
        continue-on-error: true
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        ##
        # TODO: change this to an official action or a fork on the smartcontractkit GitHub org.
        # Adding in order to support multiple --out-format args so we can generate a JSON file
        # for SonarQube consumption.
        ##
        uses: chainchad/golangci-lint-action@
        # any scheduled run or push, but skip PRs from release branches
        if: github.event.schedule != '' || github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'release/'))
        with:
          version: v1.50.1
          args: --out-format checkstyle:report.json
          only-new-issues: ${{github.event.schedule == ''}} # show only new issues, unless it's a scheduled run
